Project4: Knight.o Weapon.o Random.o project4.o
	g++ Knight.o Weapon.o Random.o project4.o -o Project4

Knight.o: Knight.cpp Knight.h
	g++ -c Knight.cpp

Weapon.o: Weapon.cpp Weapon.h
	g++ -c Weapon.cpp

project4.o: project4.cpp
	g++ -c project4.cpp 

clean: 
	rm *.o Project4
