joustproject: knight.o Random.o weapon.o main.o
	g++ knight.o Random.o weapon.o main.o -o joustproject

knight.o: knight.cpp knight.h
	g++ -c knight.cpp

Random.o: Random.cpp Random.h
	g++ -c Random.cpp

weapon.o: weapon.cpp weapon.h
	g++ -c weapon.cpp

clean:
	rm *.o joustproject




